name: Building Deployment Package 

on: 
  workflow_call:
    inputs:
      module: 
        required: true
        type: string
      custom_src_subfolder: 
        required: false 
        type: string
    secrets:
      CLOUD_DB_NAME:
        required: true
      CLOUD_DB_USER:
        required: true
      CLOUD_DB_PASSWORD:
        required: true
      CLOUD_DB_HOST:
        required: true
      CLOUD_DB_PORT:
        required: true
      BUCKET_NAME:
        required: true
      TRAINING_TABLE:
        required: true
      CONFIG_CRYPTOCURRENCIES:
        required: true
      API_ACCESS_KEY: 
        required: true
      API_SECRET_KEY: 
        required: true
      STABLECOIN: 
        required: true
      CONFIG_CLOUD_ACCESS_KEY_ID:
        required: true
      CONFIG_CLOUD_SECRET_ACCESS_KEY:
        required: true
    outputs:
      archive_name:
        value: ${{ jobs.build.outputs.archive_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      archive_name: ${{ steps.package.outputs.archive_name }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Package module & method
        id: package 
        env:
          CLOUD_DB_NAME: ${{ secrets.CLOUD_DB_NAME }}
          CLOUD_DB_USER: ${{ secrets.CLOUD_DB_USER }}
          CLOUD_DB_PASSWORD: ${{ secrets.CLOUD_DB_PASSWORD }}
          CLOUD_DB_HOST: ${{ secrets.CLOUD_DB_HOST }}
          CLOUD_DB_PORT: ${{ secrets.CLOUD_DB_PORT }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          TRAINING_TABLE: ${{ secrets.TRAINING_TABLE }}
          CONFIG_CRYPTOCURRENCIES: ${{ secrets.CONFIG_CRYPTOCURRENCIES }}
          API_ACCESS_KEY: ${{ secrets.API_ACCESS_KEY }}
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}  
          STABLECOIN: ${{ secrets.STABLECOIN }}      
          CLOUD_ACCESS_KEY: ${{ secrets.CONFIG_CLOUD_ACCESS_KEY_ID }}
          CLOUD_SECRET_KEY: ${{ secrets.CONFIG_CLOUD_SECRET_ACCESS_KEY }}  
        run: |
          set -e 

          MODULE="${{ inputs.module }}"
          SUBFOLDER="${{ inputs.custom_src_subfolder }}"
          DEPLOY_DIR="deployment"
          MODULE_DIR="$DEPLOY_DIR/${MODULE,,}"
          ARCHIVE_NAME="${{ inputs.module }}_deployment.tar.gz"

          echo "Building deployment for module: $MODULE"
          echo "Custom subfolder: ${SUBFOLDER:-none}"
          
          # Clean previous runs 
          rm -rf "$DEPLOY_DIR" "$ARCHIVE_NAME"
          mkdir -p "$MODULE_DIR/config" "$MODULE_DIR/src" 

          [ -d "$MODULE_DIR/tests" ] || mkdir -p "$MODULE_DIR/tests"
          
          echo "Writing config.json"
          cat <<EOF > "$MODULE_DIR/config/config.json"
          {
            "module": "$MODULE",
            "deployment_date": "$(date -u +%Y-%m-%dT%H%M%SZ)",
            "CLOUD_DB_NAME": "$CLOUD_DB_NAME",
            "CLOUD_DB_USER": "$CLOUD_DB_USER",
            "CLOUD_DB_PASSWORD": "$CLOUD_DB_PASSWORD",
            "CLOUD_DB_HOST": "$CLOUD_DB_HOST",
            "CLOUD_DB_PORT": "$CLOUD_DB_PORT",
            "bucket_name": "$BUCKET_NAME",
            "training_table": "$TRAINING_TABLE",
            "stablecoin": "$STABLECOIN",
            "cryptocurrencies": $CONFIG_CRYPTOCURRENCIES,
            "$CLOUD_ACCESS_KEY_NAME": "$CLOUD_ACCESS_KEY",
            "$CLOUD_SECRET_KEY_NAME": "$CLOUD_SECRET_KEY",
            "config": {
              "API": {
                "AK": "$API_ACCESS_KEY",
                "SK": "$API_SECRET_KEY"
              }
            }
          }
          EOF

          if [[ -z "$SUBFOLDER" || "$SUBFOLDER" == "<none>" ]]; then
            SRC_DIR="$MODULE/src"
          else
            SRC_DIR="$MODULE/src/$SUBFOLDER"
          fi

          echo "Checking source dir: $SRC_DIR"
          if [ -d "$SRC_DIR" ]; then 
            echo "Source directory exists, Copying files..."
            cp -r $SRC_DIR/* "$MODULE_DIR/src/" 2>/dev/null || echo "No src files found"
          else
            echo "Source directory $SRC_DIR does not exist"
          fi

          if [ -d "$MODULE/tests" ]; then
            echo "Copying tests"
            cp -r "$MODULE/tests" "$MODULE_DIR/"
          fi

          if [ -d "jars" ]; then 
            echo "Compressing jars/ into jars.tar.gz"
            tar -czf jars.tar.gz jars 
            cp -r jars.tar.gz "$DEPLOY_DIR/"
          else
            echo "Error: root-level 'jars' folder is missing"
            exit 1
          fi

          if [ -d "Airflow_Schedule" ]; then 
            echo "Compressing Airflow_Schedule int airflow_schedule.tar.gz"
            tar -czf airflow_schedule.tar.gz Airflow_Schedule
            cp -r airflow_schedule.tar.gz "$DEPLOY_DIR/"
          else
            echo "Error: root-level 'Airflow_Schedule/' folder is missing."
            exit 1
          fi
          
          if [ -d "method" ]; then
            echo "Copying method/"
            cp -r method "$DEPLOY_DIR/"

            echo "Injecting config.json into Logs/, Result/, and Archive/ folders.."
            CONFIG_PATHS=("Logs" "Result" "Archive")

            for folder in "${CONFIG_PATHS[@]}"; do
              TARGET_DIR="$DEPLOY_DIR/method/$folder/config"
              mkdir -p "$TARGET_DIR"

              echo "Writing config.json to $TARGET_DIR"
              cat <<EOF > "$TARGET_DIR/config.json"
          {
            "module": "$MODULE",
            "deployment_date": "$(date -u +%Y-%m-%dT%H%M%SZ)",
            "CLOUD_DB_NAME": "$CLOUD_DB_NAME",
            "CLOUD_DB_USER": "$CLOUD_DB_USER",
            "CLOUD_DB_PASSWORD": "$CLOUD_DB_PASSWORD",
            "CLOUD_DB_HOST": "$CLOUD_DB_HOST",
            "CLOUD_DB_PORT": "$CLOUD_DB_PORT",
            "bucket_name": "$BUCKET_NAME",
            "training_table": "$TRAINING_TABLE",
            "stablecoin": "$STABLECOIN",
            "cryptocurrencies": $CONFIG_CRYPTOCURRENCIES,
            "$CLOUD_ACCESS_KEY_NAME": "$CLOUD_ACCESS_KEY",
            "$CLOUD_SECRET_KEY_NAME": "$CLOUD_SECRET_KEY",
            "config": {
              "API": {
                "AK": "$API_ACCESS_KEY",
                "SK": "$API_SECRET_KEY"
              }
            }
          }
          EOF
            done
          else
            echo "Error: root-level 'method/' folder is missing!"
            exit 1
          fi

          echo "Deployment folder structure:"
          find "$DEPLOY_DIR" -type f || echo "Deployment folder is empty"
          if [ -z "$(find "$DEPLOY_DIR" -type f)" ]; then
            echo "Nothing to archive. Exiting."
            exit 1
          fi

          find "$DEPLOY_DIR" -type f | sort > deployment_manifest.txt 

          echo "Creating archive: $ARCHIVE_NAME"
          tar -czf "$ARCHIVE_NAME" -C . deployment/

          echo "Archive content:"
          tar -tzf "$ARCHIVE_NAME"
          echo "archive_name=$ARCHIVE_NAME" >> $GITHUB_OUTPUT

      - name: Upload deployment archive
        uses: actions/upload-artifact@v4
        with:
          name: deployment-archive
          path: ${{ steps.package.outputs.archive_name }}
          retention-days: 1

      - name: Upload deployment manifest
        uses: actions/upload-artifact@v4
        with:
          name: deployment-manifest-${{ inputs.module }}
          path: deployment_manifest.txt
          retention-days: 1