name: Server cleanup

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string
    secrets:
      SERVER_USERNAME:
        required: true
      SERVER_HOST:
        required: true
      SERVER_SSH_KEY:
        required: true

jobs:
  cleanup: 
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: add SERVER host to known_hosts
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts

      - name: Server cleanup
        id: cleanup
        env:
          MODULE: ${{ inputs.module }}
          SERVER_USER: ${{ secrets.SERVER_USERNAME }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$SERVER_USER@$SERVER_HOST" bash -s <<EOF
            set -e
            MODULE="${{ inputs.module }}"
            sudo rm /tmp/deploy_\$MODULE_deploy_*
            sudo rm -rf ~/temp_deployment_deploy_*
            cd ~/
            sudo rm -rf *.tar.gz
          EOF